### ISSUE TITLE
Cannot use SharpSimpleNLG classes in .NET Core

### ISSUE THREAD

**Issue by ccaneke** [nickhodge/SharpSimpleNLG#10]
I added the latest version of the nuget package SharpSimpleNLG to my .NET Core application using `dotnet add package SharpSimpleNLG`, and it shows that a reference to that package was added successfully to the .csproj file in the project. However I can't use a using directive to resolve any of the namespaces in the SharpSimpleNLG package such as SharpSimpleNLG. In other words, `using SharpSimpleNLG;` does not work.

Does SharpSimpleNLG only work for .NET standard, and not .NET Core? Maybe this is why I can't use the package in my .NET Core application.

**Comment by nickhodge** [comment]
I have just updated the NuGet to .NET Standard 2.0 

This is version 1.3.0 ... can you see if this now works for you?

**Comment by nickhodge** [comment]
Works for me on a .NET Core 3.0 console app

**Comment by ccaneke** [comment]
@nickhodge It now works, thanks for the update.
