### ISSUE TITLE
Any thoughts on using IKVM.NET to generate .NET dll to convert the simplenlg Java lib?

### ISSUE THREAD

**Issue by as-ghub** [nickhodge/SharpSimpleNLG#7]

**Comment by nickhodge** [comment]
Feel free to give it a go. I chose not to follow this route because:

1. I wanted to learn how to do a Java to C# conversion project
2. I needed deploy inside a desktop application, and size was a consideration: especially as I was already transporting large NLP datasets (eg: WordNet)
