### ISSUE TITLE
Failed to run ClauseTest.testForm

### ISSUE THREAD

**Issue by zakanych** [nickhodge/SharpSimpleNLG#8]
When running the test in **ClauseTest.cs testForm()** it fails on validating the **IMPERATIVE** feature
![image](https://user-images.githubusercontent.com/9998390/56906667-66e8de80-6aab-11e9-8986-09e47949d3b4.png)

Is there something I'm doing wrong?

**Comment by nickhodge** [comment]
The Unit test is failing. When I originally did the port, not all the Java unit tests were working.

So your mileage may vary. 

I note the original project has had some updates ... but I do not have the time nor the reason to update myself.
